sudo: required
language: go
go:
  - '1.11'
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - go test ./...
after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  # Auth flow
  - bash auth-gcloud.sh
  # Deployment if master branch and !PR
  - bash deploy.sh
