version: '3.1'
services:
    mongo:
        image: mongo:3.2
    regexrace:
        build: .
        ports:
            - "80:8080"
        volumes:
            - .:/go/src/github.com/thylong/regexrace
        links:
            - mongo
        environment:
            TOKEN_TTL: 5
            TIMER_DURATION: 5
